### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by SenorSmartyPants** [Neurrone/beets-audible#1]
Add more options

- enable/disable output of desc.txt
- enable/disable output of narrator.txt
- enable/disable including narrator in artists field

**Comment by Neurrone** [comment]
Thanks for the suggestion.

I'm not opposed in principle to adding more configurability, but I'm trying to figure out how to do so without adding too many options.

In the case of enabling / disabling the writing of desc and reader.txt, that could be 2 booleans that control that behaviour. That's probably something I could implement quickly in the coming weekend or the week after next once I have a few mins.

Disabling inclusion of narrator in artists is something I'm unsure about, because this then opens the doors to requests for arbitrary mappings of metadata to tags. For example, that could be implemented as a simple boolean but would not be feasible in the long run to support more customization.

Customizing tag metadata like this will only happen later on, once i figure out how this should be configured.

**Comment by SenorSmartyPants** [comment]
These features were added in #16  and #17
