### ISSUE TITLE
Audible Plugin Doesnt Work

### ISSUE THREAD

**Issue by mslmn** [Neurrone/beets-audible#55]
Have tried this on both a local installation and via docker compose. it returns `Error: MusicBrainz not reachable in release search with query` but doesn't work or run any searches with Audible. 

Running beet version returns `plugins: audible, copyartifacts, edit, fromfilename, scrub web`

**Comment by Neurrone** [comment]
The MusicBrainz not reachable error is an expected result, since the readme's instructinos causes Musicbrinz lookup to be disabled by setting it to a non-existent address. There is no built-in way of disabling it.

Could you run the import with the verbose or debug flag to get more info on what's going on?

**Comment by Neurrone** [comment]
There is nothing wong with the plugin. Doing the [same search on Audible](https://www.audible.com/no-search-results?keywords=Palestine%2C+Zionism%2C+and+the+Arab-Israeli+Conflict) returns no results.
